### PR TITLE
Add Spain Public Holidays

### PR DESCRIPTION
**Pull request by jmontane**

### CODE REVIEW

**Comment by ypid** [comment]
Hi

Thanks. The format looks good. One thing, you already included the cooridnates for the states, can you make that machine reachable because the tools in this repo need it to test the definition.

Example: https://github.com/opening-hours/opening_hours.js/blob/master/holidays/ch.yaml
Docs: https://github.com/opening-hours/opening_hours.js/blob/master/holidays/README.md

**Comment by jmontane** [comment]
Thanks,

I'm not a programmer, so I'm not fluent with git commands. I fixed few dates too.

Joan Montané

**Comment by ypid** [comment]
Looks good to me, thanks. Had to fix a one tiny mistake. Please check the following generated PH list for AN:

```
$ ./PH_SH_exporter.js --from 2020 --to 2020 /tmp/out -c es -p -v -r an                                                                  
2020-01-01 Año Nuevo
2020-01-06 Epifanía del Señor
2020-04-10 Viernes Santo
2020-05-01 Fiesta del Trabajo
2020-08-15 Asunción de la Virgen
2020-10-12 Fiesta Nacional de España
2020-11-01 Todos los Santos
2020-12-06 Día de la Constitución Española
2020-12-08 La Immaculada Concepción
2020-12-25 Natividad del Señor
```

**Comment by jmontane** [comment]
Oh, I see Andalucía state code AN was missing. I'm sorry

"2020-02-28 Día de Andalucía", is missing in your list.

**Comment by ypid** [comment]
Fixed. In my review, I missed that the `_state_code` needs to be lower case. I have a script check for this now so it cannot slip my review anymore.

```Shell
$ ./PH_SH_exporter.js --from 2020 --to 2020 /tmp/out -c es -p -v -r an
2020-01-01 Año Nuevo
2020-01-06 Epifanía del Señor
2020-02-28 Día de Andalucía
2020-04-09 Jueve Santo
2020-04-10 Viernes Santo
2020-05-01 Fiesta del Trabajo
2020-08-15 Asunción de la Virgen
2020-10-12 Fiesta Nacional de España
2020-11-01 Todos los Santos
2020-12-06 Día de la Constitución Española
2020-12-08 La Immaculada Concepción
2020-12-25 Natividad del Señor
```

**Pull request merged**
