### PR TITLE
fix: add i18next-client as dependency

### PR DESCRIPTION
**Pull request by napei**
From #378 

For use with NPM as a package `i18next-client` needs to be a dependency. This doesn't break anything but it makes it questionable if it still needs to be a peerDependency. Peer deps are not installed by default either, so this will work for everyone. When shipped as a bundled `.js` file the package.json is irrelevant, so it makes sense for it to just be a normal dependency.

@ypid let me know if you want it removed from peerDeps too and I'll amend.

### CODE REVIEW

**Comment by ypid** [comment]
> let me know if you want it removed from peerDeps too and I'll amend.

I think it would make sense to remove it from peerDeps. Or do you see a reason to keep it there as a duplicate?

**Comment by napei** [comment]
> I think it would make sense to remove it from peerDeps. Or do you see a reason to keep it there as a duplicate?

Gone. Would this also remove the need for `npm run install-peers` under `make dependencies-get`?

**Comment by ypid** [comment]
> remove peer deps again (don't know why it broke) 

Because you reverted it in 1a483e4bd7a666178aca5904439a85437d6d1078? I squash merged this PR. No need to have four commits in the git history for this.

GitHub does not show this commit as merged because of the squash I did and I guess my commit message did not match the pattern of a merge message. I will look out for this next time.

**Comment by napei** [comment]
> > remove peer deps again (don't know why it broke) 
> 
> Because you reverted it in 1a483e4bd7a666178aca5904439a85437d6d1078? I squash merged this PR. No need to have four commits in the git history for this.
> 
> GitHub does not show this commit as merged because of the squash I did and I guess my commit message did not match the pattern of a merge message. I will look out for this next time.

Reverted the commit because my brain decided that rebasing the branch was not gonna happen for some reason 😂

For whatever reason it changed something in package lock that broke CI hence the revert.

I always let GitHub manage the merge and specify squash and merge. Makes life a lot simpler.

> Gone. Would this also remove the need for npm run install-peers under make dependencies-get as well as that dependency?

About the peer deps script?

**Comment by ypid** [comment]
> About the peer deps script?

I overlooked that. Good idea, I fixed it in #384.

> I always let GitHub manage the merge and specify squash and merge. Makes life a lot simpler.

Over at DebOps, we have a policy (https://docs.debops.org/en/master/meta/policy/code-signing-policy.html) that just follow for all projects.

**Pull request closed without merging**
