### PR TITLE
Public holidays for Switzerland

### PR DESCRIPTION
**Pull request by simonpoole**
This is based on 
https://www.bj.admin.ch/dam/data/bj/publiservice/service/zivilprozessrecht/kant-feiertage.pdf

Compared to https://github.com/opening-hours/opening_hours.js/pull/236 (which it is copied from) it uses the nominatim name field for canton names, indicates mulri-lingual names for the holidays themselves and adds missing cantonal level entries.

It is currently missing Fahrtsfest in the Canton Glarus and Lundi du Jeûne fédéral in the Canton Vaud (not sure if they can be reasonably specified in the current format). It does not (and currently cannot) take municipality level differences in to account.

### CODE REVIEW

**Comment by simonpoole** [comment]
Added more languages to the nominatim url not sure if it means anything though

**Comment by ypid** [comment]
Thanks very much @simonpoole! Could you add the `_nominatim_url` and `_state_code` for all the cantons? Refer to wikipedia for the codes: https://en.wikipedia.org/wiki/Cantons_of_Switzerland and osm for lat and lon. You might also be able to script this further which would be welcome.

Example: https://github.com/opening-hours/opening_hours.js/commit/8adde09884491a20108c72df39c0c751d6116a71

After that, `./PH_SH_exporter.js --from 2017 --to 2017 /tmp/out -c ch -p -v -r 'zh'` can be used to test the PH definitions:

```
2017-01-01 Neujahrstag/Nouvel an/Capo d'anno
2017-01-02 Berchtoldstag/2 janvier
2017-04-14 Karfreitag/Vendredi saint
2017-04-17 Ostermontag/Lundi de Pâques/Lunedi di Pasqua
2017-05-01 Tag der Arbeit//Festa dei lavoratori
2017-05-25 Auffahrt/Ascension/Ascensione
2017-06-05 Pfingstmontag/Lundi de Pentecôte/Lunedi di Pentecoste
2017-08-01 Bundesfeiertag/Jour de la fête nationale/Giorno festivo federale
2017-12-25 Weihnachtstag/Noël/Natale
2017-12-26 Stephanstag/Saint-Etienne/Santo Stefano
```

(`make opening_hours.js` and `pushd holidays && ./populate_nominatim_cache -d` is needed before).

> Added more languages to the nominatim url not sure if it means anything though.

The `state` and `country` are not language independent. Refer to the [docs](https://github.com/opening-hours/opening_hours.js/tree/master/holidays) for details.

PS: You can rebase on https://github.com/opening-hours/opening_hours.js/commits/%23238 if possible.

**Comment by robinmetral** [comment]
Hi @simonpoole @ypid, any developments on this PR? I'd love to see this implemented :slightly_smiling_face:

**Comment by simonpoole** [comment]
@robinmetral last time I checked the build system for the contents of the repo didn't work and there, are, believe it or not, limits to the amount of time that I, or matter of fact other people that have looked at the issue, are willing to spend on this.

**Comment by ypid** [comment]
@simonpoole is right. Time is always against us.

> build system for the contents

Can’t reproduce this. Fortunately the only thing holding back this PR is:

> Could you add the _nominatim_url and _state_code for all the cantons?

I am willing to do everything else. I just don’t want to work on holiday definitions for every single country myself. My involvement for every single country is already required as I maintain this library. Still I need to draw a line at some point.

**Comment by robinmetral** [comment]
> Could you add the _nominatim_url and _state_code for all the cantons?

I'll do it :hand:

**Comment by robinmetral** [comment]
If that's okay with you @simonpoole of course

**Comment by simonpoole** [comment]
> 
> 
> If that's okay with you @simonpoole of course

Sure.

**Comment by robinmetral** [comment]
How do we do this? Could you give me [push access](https://help.github.com/articles/committing-changes-to-a-pull-request-branch-created-from-a-fork/) to `PH_Switzerland`? Or do I create a new PR?

**Comment by simonpoole** [comment]
@robinmetral I believe pushing to a PR is only possible if you are a maintainer of the upstream repo. But IMHO you can form my repo, make a PR against that which I can merge, at least that doesn't seem to be  ruled out as far as I can tell.

**Comment by ypid** [comment]
You can just push additional commits to your branch PH_Switzerland and they will appear here.

**Comment by ypid** [comment]
@robinmetral: Please create a new PR. It is not like we don't already have two for PH CH :-). But please base it on the branch from Simon.

**Comment by sfkeller** [comment]
I'd be interested to add holidays for 2020 - but this PR and issue seem to be completely outdated... :-( 

P.S. Here are similar projects: 
Calculate holiday dates in #Python 'pip holidays': 
https://pypi.org/project/holidays/ 
Ported to #PostgreSQL as 'pgsql_holidays': 
https://github.com/christopherthompson81/pgsql_holidays .

**Comment by ypid** [comment]
@sfkeller 

I am aware that the current approach is not ideal. Ideas can be collected in https://github.com/opening-hours/opening_hours.js/issues/300. Feel free to add yours too when you have something better than what we already found.

**Comment by sfkeller** [comment]
Thx. 

BTW. There's hope that this weekend somebody at https://wiki.openstreetmap.org/wiki/Karlsruhe_Hack_Weekend_February_2020#Schedule_.2F_Zeitplan has time to care for this issue and e.g. to install the dev environment and to rebase the code.

You mention ideas and there a new API and common sources of holidays is being discussed. But what's IMHO much more important, is to define and implement a common (file) format to encode the holidays.

**Comment by HolgerJeromin** [comment]
>  But what's IMHO much more important, is to define and implement a common (file) format to encode the holidays.

https://www.xkcd.com/927/

**Comment by sfkeller** [comment]
> https://www.xkcd.com/927/

Nope. Finding a common format to avoid duplicated efforts is not the same as the "game of standards" finding the least common denominator...

**Comment by ypid** [comment]
> There's hope that this weekend somebody 

In that case I guess the work from https://github.com/opening-hours/opening_hours.js/pull/283 should be picked up.

> You mention ideas and there a new API and common sources of holidays is being discussed.

#300 is dedicated for this discussion. Please do not mix topics here.

**Comment by sfkeller** [comment]
Dear Maintainer(s) / @ypid (?): 
Hope you've seen this PR https://github.com/opening-hours/opening_hours.js/pull/321 ?
IMHO this would also close this PR.

**Comment by ypid** [comment]
@sfkeller I guess I am the only maintainer since 2013-09 :) Still keeping up somehow.

Seen that. Looks good. You are also right, I will close this PR now to avoid confusion. Thanks to all people working on PH definitions for ch!

**Pull request closed without merging**
