### PR TITLE
Made the time table look prettier (per hour marks) and CSS cleanup

### PR DESCRIPTION
**Pull request by dex2000**
added some separators for hours in time table.
additional simplifie some css-rules

### CODE REVIEW

**Comment by dex2000** [comment]
what "assign" is mean? :)
I have no plan how to merge it on github-website

**Comment by ypid** [comment]
Looks good, thanks. :+1: I deployed your changes on http://ypid.de/~osm/ for now. Assigning allows to declare a person of a organization on GitHub (https://github.com/opening-hours in this case) to handle a particular PR or issue. Technically I should have assigned me because I reviewed and merged your PR.

**Comment by dex2000** [comment]
uh forgot unknown times, will build another PR for that, but not today i think.

**Comment by ypid** [comment]
No problem. Thanks for your work :+1:

**Pull request merged**
