### PR TITLE
Add fi.yaml based on be.yaml, se.yaml examples

### PR DESCRIPTION
**Pull request by Virtakuono**
Hi there and thanks for the good work!

It would be great to have the public holidays for Finland as well, these are pretty much the same as for Sweden, apart from independence day, and different naming of holidays. I hope the enclosed file can be helpful in this.

Cheers,

Juho

### CODE REVIEW

**Comment by ypid** [comment]
Looks good to me, thanks.

Can you check that these are the expected public holidays?

```
./PH_SH_exporter.js --from 2019 --to 2020 /tmp/out -c fi -v --public-holidays
2019-01-01 uudenvuodenpäivä - nyårsdagen
2019-01-06 loppiainen - trettondedagen
2019-04-19 pitkäperjantai - långfredagen
2019-04-21 pääsiäispäivä - påskdagen
2019-04-22 toinen pääsiäispäivä - annandag påsk
2019-05-01 vappu - första maj
2019-06-09 helluntai - pingst
2019-06-22 juhannuspäivä - midsommarafton
2019-11-02 pyhäinpäivä - alla helgons dag
2019-12-06 itsenäisyyspäivä - självständighetsdagen
2019-12-25 joulupäivä - juldagen
2019-12-26 toinen joulupäivä - annandag jul
2020-01-01 uudenvuodenpäivä - nyårsdagen
2020-01-06 loppiainen - trettondedagen
2020-04-10 pitkäperjantai - långfredagen
2020-04-12 pääsiäispäivä - påskdagen
2020-04-13 toinen pääsiäispäivä - annandag påsk
2020-05-01 vappu - första maj
2020-05-31 helluntai - pingst
2020-06-20 juhannuspäivä - midsommarafton
2020-10-31 pyhäinpäivä - alla helgons dag
2020-12-06 itsenäisyyspäivä - självständighetsdagen
2020-12-25 joulupäivä - juldagen
2020-12-26 toinen joulupäivä - annandag jul
```

**Comment by Virtakuono** [comment]
Hi Robin,

thanks for moving the ball forward.

I checked the holidays for 2019, as well as the variable ones (pitkäperjantai, pääsiäispäivä, toinen pääsiäispäivä, helluntai, juhannuspäivä by their Finnish names.) for 2020. All of them seem to coincide with the calendar that is served by Google search.

Cheers,

Juho

**Comment by Virtakuono** [comment]
Kudos!

I was about to ask  about when does this get to openingh.openstreetmap.de, but I see it's already running there.

Keep up the good work,

Juho

**Comment by ypid** [comment]
Thanks, you are welcome ;-)

**Pull request merged**
