### PR TITLE
Some translations into Japanese, Japanese holidays added, date calculations for spring and autumnal equinoxes added (not tested)

### PR DESCRIPTION
**Pull request by Revtro**
Hello.
This is my first time using GitHub and I am still new to English and programming, so there may be some mistakes, my apologies.

On the main topic, I have translated some parts of the text into Japanese, added Japanese holidays, and added a function to calculate the date of one of those Japanese holidays, the spring and autumnal equinoxes. However, the last one may cause an error because I could not test it properly.

Once again, I apologize if I have caused inconvenience.

Thank you very much.

### CODE REVIEW

**Comment by Revtro** [comment]
As an additional note regarding Japanese holidays, most stores shorten their hours or do not open during the year-end and New Year's holidays even if they are usually open on holidays.
I do not know how to express this in the program.

**Comment by ypid** [comment]
> I do not know how to express this in the program.

We have that in Germany was well. So from what I know from Germany, we cannot provide a generic solution. The mapper will have to encode that into the opening_hours value.

You overwrote `src/holidays/index.js` and added the functions there. That is not how it works ;-) I reverted the file and copied over the the code you added accordingly. The functions you wrote actually seem to work ;-) see:

```
./scripts/PH_SH_exporter.js --from 2022 --to 2023 /tmp/out -c jp -p -v
jp:                  
2022-01-01 元日      
2022-01-10 成人の日
2022-02-11 建国記念の日
2022-02-23 天皇誕生日
2022-03-21 春分の日
2022-04-29 昭和の日
2022-05-03 憲法記念日  
2022-05-04 みどりの日  
2022-05-05 こどもの日                                                                                                         
2022-07-18 海の日                                              
2022-08-11 山の日                                              
2022-09-19 敬老の日                                                                                                           
2022-09-23 秋分の日                                                                                                           
2022-11-03 文化の日                                                                                                           
2022-11-14 スポーツの日
2022-11-23 勤労感謝の日
2023-01-01 元日                                                
2023-01-09 成人の日
2023-02-11 建国記念の日                                                                                                       
2023-02-23 天皇誕生日                                          
2023-03-21 春分の日                                            
2023-04-29 昭和の日
2023-05-03 憲法記念日                                          
2023-05-04 みどりの日                                          
2023-05-05 こどもの日                                                                                                         
2023-07-17 海の日
2023-08-11 山の日                                                                                                             
2023-09-18 敬老の日                                                                                                           
2023-09-23 秋分の日                                                                                                           
2023-11-03 文化の日                                                                                                           
2023-11-13 スポーツの日
2023-11-23 勤労感謝の日
```

I tried to push the fixes to this pull request but accidentally pushed the master commit which closed this PR. I reopened as  #432

**Comment by ypid** [comment]
@Revtro Thanks very much for your update in https://github.com/ypid/opening_hours.js/pull/2. Nothing more for me to fix. Well done. You wrote you are new to English, programming and GitHub. Well done.

It can be tested on: https://openingh.openstreetmap.de/evaluation_tool/?lng=ja

**Comment by Revtro** [comment]
Thank you very much for all you have done for me as well, including teaching me and correcting me. I am also honored by your compliments.
I also have seen the site, and I am glad it seems I managed to work it out.

**Pull request closed without merging**
