### PR TITLE
Adding holiday dates for England and Wales

### PR DESCRIPTION
**Pull request by skifans**
Iv attempted to add dates for public holidays in England and Wales. Iv not found any full documentation but have guessed on the syntax by looking at so it would probably be wise to double check what iv done. It appears that dates should be in the month,day format. Could some also confirm weather or not it matters what order the holidays are listed, Boxing day usually follows Christmas day but in years where the 25th of December is a Sunday then they swap placed (as will happen this year [2016]) so I have placed them the way round which they occur most frequently.
Sourced from: https://www.gov.uk/bank-holidays#england-and-wales

### CODE REVIEW

**Comment by ypid** [comment]
Hey @skifans 
Thanks for your PR.

> Iv not found any full documentation

I have [updated the documentation](https://github.com/opening-hours/opening_hours.js#holidays-1) to give some examples. First you might want to check the definitions of `PH` and `SH`. https://wiki.openstreetmap.org/wiki/Key:opening_hours
Your holidays are public holidays (PH) which use a different format but you defined the PH using the SH format. Can you update that?

**Comment by skifans** [comment]
Thanks, iv put the dates into the correct format. Just to ask, iv used the dates which they would have been given to the events historically but in the UK if the event happens on a Saturday then the public holiday is moved to the Friday (And from Sunday to Monday), is this dealt with by the program or does it somehow need to be added in (or have you just been ignoring it?). School holidays here are decided on a per school basis so it would not be practical to include them in a program like this.

**Comment by ypid** [comment]
Thanks for the updated patch set.

> if the event happens on a Saturday then the public holiday is moved to the Friday (And from Sunday to Monday), is this dealt with by the program or does it somehow need to be added in (or have you just been ignoring it?)

Interesting. I have not ignored it because when I remember correctly, I was not confronted with this before. I would be happy to support it. The library is certainly flexibility enough to allow this to be done with not too big of a hassle. Checkout the [list of movable events returned by `getMovableEventsForYear`](https://github.com/opening-hours/opening_hours.js/blob/0953d98a6bd28d13ee02841124c5ac2c14384c35/opening_hours.js#L5900-L5925) (warning the file is really big which might freeze up your browser) which are used in PH definitions. Sadly at the moment because I was not aware of such PH practices, you would have to define each PH as one returned date in `getMovableEventsForYear`. When there are more instances of this for other cultures, I will probably refactor this later. So please go for it.

> School holidays here are decided on a per school basis so it would not be practical to include them in a program like this.

That’s sad for the purposes of this library. It might be theoretically possible to support this but it would have to automated. I guess there is not something like an API or Open Data for all those schools available?

Note that you made a little quoting error which GitHub shows you in the diff: https://github.com/opening-hours/opening_hours.js/pull/162/files

**Comment by ypid** [comment]
The source you linked has bank holidays in the name: https://www.gov.uk/bank-holidays#england-and-wales

I once saw people using `BH` instead of `PH` in opening_hours values. Can you maybe explain the differences if there are any or are there just `BH` in England and Wales? A good place to add this comment might be to the [opening hours talk page](https://wiki.openstreetmap.org/wiki/Talk:Key:opening_hours#BH.3F) so that others can also benefit from it.
A good place to add this comment might be to the [opening hours talk page](https://wiki.openstreetmap.org/wiki/Talk:Key:opening_hours#BH.3F) so that others can also benefit from it.

Also, seems that the data format is not as intuitive as I hoped. My bad. I wrote a [detailed documentation](https://github.com/opening-hours/opening_hours.js/blob/master/docs/holidays.md) about it. I hope this clarifies things.

**Comment by skifans** [comment]
Thanks for the new documentation, it realy is alot more useful and makes perfect sense. With regard to BH vs PH, in the UK (and possibly other countries - the you have linked to suggests that it is Commonwealth countries but I couldn't verify this - iv tried to update the Wiki but there is currently a problem with registration, il do it later when it gets sorted.), we call our public holidays, bank holidays. Additionally, it turns out I was incorrect on the dates, weather or not the holiday is a Saturday or Sunday it will be moved to a Monday (not a Friday as said earlier). As this is GB there is obviously an exception to this which Iv tried to detail bellow:
Option 1 - Christmas (25th December) and Boxing day (26th December) fall on a weekday => public holiday being observed on these dates.
Option 2 - Christmas (25th December) falls on a Friday and Boxing day (26th December) falls on a Saturday, if this happens the Boxing day bank holiday is moved to the Monday (28th December).
Option 3 - Christmas (25th December) falls of a Saturday and Boxing day (26th of December) falls on a Sunday, if this happens Christmas day is moved to Monday (28th December) and Boxing day is moved to Tuesday (29th December) to give bank holidays on the Monday and Tuesday.
Option 4 - Christmas (25th December) falls on a Sunday and Boxing day (26th December) falls on a Monday, if this happens then Boxing day is observed on the 26th and Christmas day is moved to Tuesday to the 27th of December. Note that this has the effect of switching the order in which the holidays appear.

With regard to school holidays, iv now had the time to properly research this and was unable to find an API. In the UK the schools are run under 1 of 4 systems (Faith (run by faith group), Academy (run by company but must be non for profit - is free to attend), Council (run by council) and Private (run by a for profit company or charity but charges students/parents a fee for attendance)). It turns out that council schools which make up around 30% of UK schools will all share holidays but the government has pledged that all council schools will become Academys by 2018 so this will be a short term measure. Even if you wanted to use these dates then it still would create around 30 sets of semi overlapping data for each of the councils. The government does though have a search box at https://www.gov.uk/school-term-holiday-dates but it will still take a while to get through (if you need an example postcode - EC1A 1AA will work). However, the side effect of this is that very few businesses adjust their opening times, for school holidays, it just isn't worth it due to the mass of complicated overlap and the spread means that the increase in school children isn't very much - saying this things like school buses are of course dependent on the school opening. But for less direct businesses they are far more likely to just post different opening times for August or equivalent when most of schools are on holiday.

Lastly, thanks for pointing out the problem with the quotes - im quite new to using Github for this forks/issues instead of like any other file storage so apologies if this is a stupid question. I see the problem on the diff but when I go to edit the fork (?) I do see them, obviously they have been moved down and are now on lines 2807-2810 (see: http://i.imgur.com/f8S9sD6.png) as iv placed the holidays for GB above them, should I try and add them back anyway or am I missing something?

**Comment by ypid** [comment]
> Thanks for the new documentation, it realy is alot more useful and makes perfect sense.

You are welcome :wink:

> we call our public holidays, bank holidays.

Thanks for the clarification.

> turns out I was incorrect on the dates, weather or not the holiday is a Saturday or Sunday it will be moved to a Monday (not a Friday as said earlier)

I kind of like this convention although it adds complexity but it also gets you more public holidays.

> Option 4

Kind of wired because of the reordering but OK. As far as I remember, sorted holidays are only required for `SH` currently. I think I tried this already when `PH` switching the order and this is supported.

> By my understanding from your link, the movable function only returns get last x or get first y in  month. I cant think of an algorithm which would use this (even for one which isn't the exception above) as the day the holiday is on changes. Do you have any ideas?

That is correct. An algorithm for this shouldn’t be too difficult for a programmer. You can just implement the four options you have mentioned. Are you fluent in JavaScript or want to give it a try? If you want, you can leave this task for me.

Regarding the school holidays. Thanks you very much for the clarification. So implementing support for council schools will probably not pay off. The search box does not look too bad if one really wants to support the school holidays. But as you said, that would require some work. And because most businesses don’t really adopt to `SH`, I guess we can leave it as is currently and not implement `SH` support.

> Lastly, thanks for pointing out the problem with the quotes - im quite new to using Github for this forks/issues

Thanks for opening the pull request then. I try to look on peoples profiles to find out if they might be new to GitHub. The GitHub web interface is not the best way to edit files. Normally, you would edit them on your computer but that requires some software and knowledge. I guess the GitHub web interface does not like big source files. However, I can fix that up for you.

Can you update your PR to make it work with [Nominatim as documented](https://github.com/opening-hours/opening_hours.js/blob/master/docs/holidays.md)?

**Comment by ypid** [comment]
@skifans Do you need any additional support from my side?

**Comment by skifans** [comment]
Deeply sorry this has taken so long, iv been very busy with current exams irl. Il try and get something done over the weekend (last 1 is tomorrow), Sorry.

**Comment by ypid** [comment]
Don’t worry. There is no time pressure in any way :wink: I was just checking :smile:

**Comment by skifans** [comment]
Thanks for understanding - I still haven't got round to doing it for personal reasons but il try and finish ASAP.

**Comment by ypid** [comment]
Thanks :)

**Comment by simon04** [comment]
Adapted syntax (due to 027814675e0b128cc4a174bd9cbee33c2e1bf1a3): `holidays/gb.yaml`:
```yaml
'England & Wales':
  PH:
    'New Years day': [1, 1]
    'Good friday': [easter, -2]
    'Easter Monday': [easter, 1]
    'Early May bank holiday': [firstMayMonday, 0]
    'Spring bank holiday': [lastMayMonday, 0]
    'Summer bank holiday': [lastAugustMonday, 0]
    'Christmas': [12, 25]
    'Boxing day': [12, 26]
```

**Pull request closed without merging**
