### PR TITLE
Update holydays fr 2023 (zone A, B, C and Corse)

### PR DESCRIPTION
**Pull request by vinber**

### CODE REVIEW

**Comment by ypid** [comment]
Nice! Can you fix the warning (CI treads it as error) and optionally squash your commits into one?

**Comment by vinber** [comment]
> Nice! Can you fix the warning (CI treads it as error) and optionally squash your commits into one?

I need to learn how to do it (I "understand" how to write SH but CI (???), squash my commits (???) ...).
I ask to a real dev (i'm not dev :D) and when it's ok i'll dot it (perhaps with SH 2024, 2025, ...).

**Comment by vinber** [comment]
i correct errors in CI.
and you can squash my commits on merge.

Thanks

**Review by ypid — APPROVED** [review]

**Comment by ypid** [comment]
Merged and deployed to https://openingh.openstreetmap.de/evaluation_tool/?EXP=SH&lat=47.7769&lon=7.1844&mode=0&DATE=1675716720000. Github does not show the merge because I did not push the squash to your branch. I did the merge locally on my machine so I don’t use the Web UI merge and squash stuff.

I tested it quickly and it seems there is some issue. I cannot look into this right now unfortunately. If you or someone finds the issue, I can review and merge it.

**Pull request closed without merging**
