### PR TITLE
Update SH France

### PR DESCRIPTION
**Pull request by blef00fr**

### CODE REVIEW

**Comment by ypid** [comment]
Hi

Thanks for updating. The history should say in the file. It would be pretty easy for me to remove that with a script instead of doing it manually. See https://github.com/opening-hours/opening_hours.js/blob/master/holidays/README.md#holiday-definition-format-sh

> Also note that past year definitions can be removed from the definition as long as the SH dataset can be regenerated as a whole by Free Software without depending on none-cached resources and as long as the unit tests pass which might where written against previous holidays. Two years in the past should be more then enough for the typical use cases of the library. In the far future, a compile time option might be provided to make this configurable to also make historian’s happy.

I tried to fix up your pull request but messed with your master branch somehow and now I cannot force push the rebased version. So I opened #354. Please review it. It replaces this pull request which I will now close.

**Comment by ypid** [comment]
Your unaltered work (except the commit message) is in 69aff77663d037fe868137a416fc558d3eacd4ac

**Comment by blef00fr** [comment]
Hello Robin
I'm sorry for the work I'm giving you, I tried to do my best, but I'm really not good with Github, I must have screwed up somewhere.
I don't understand what you want from me now.
If you can't update fr.yaml, forget it, I'll start all over again after I've seriously learned how Github works.

**Comment by ypid** [comment]
All good. I reworked your work to a state where I can merge it. I am only waiting on your feedback if it looks good.

If you could check #354 and specifically the diff https://github.com/opening-hours/opening_hours.js/pull/354/files
then comment on this pull request (#354).

**Pull request closed without merging**
