### PR TITLE
New Zealand public holidays

### PR DESCRIPTION
**Pull request by Mortein**
Added the 10 statutory holidays in New Zealand.

Technically, there's an 11th "provincial holiday", which varies by province. Provinces have since been replaced with Regions, but the holiday is still official. Regions somewhat match the old Provinces, but they are different. [Wikipedia explains this much better than I can.](https://en.wikipedia.org/wiki/Public_holidays_in_New_Zealand#Provincial_anniversary_days) As the `state` field from Nominatim contains Region, I'm not sure it's easily possible to match the provincial holidays to their correct locations.

### CODE REVIEW

**Comment by Mortein** [comment]
If you'd like an accompanying issue, let me know and I'll create it.

**Comment by Mortein** [comment]
The [legislation for Anzac Day](http://legislation.govt.nz/act/public/1966/0044/latest/DLM379806.html) uses Anzac Day, not ANZAC Day.

[Wikipedia](https://en.wikipedia.org/wiki/Public_holidays_in_New_Zealand) and its sources (including the [Holidays Act](http://legislation.govt.nz/act/public/2003/0129/latest/DLM237120.html) and [Employment New Zealand](https://www.employment.govt.nz/leave-and-holidays/public-holidays/public-holidays-and-anniversary-dates/)) are incorrect.

**Comment by ypid** [comment]
You made my day. First holiday definition PR in a while that looks good as is and even adds a unit test. Thank you :)

> If you'd like an accompanying issue, let me know and I'll create it.

Holiday definitions (and even worse school holidays) are not meant to be logical or easy for GIS systems. If you can provide a solution based on OSM data, I can merge it, otherwise, I am afraid, I cannot spend the time to work out solutions for all special cases of all countries in the world. Also, please have a look at #300.

```Shell
./PH_SH_exporter.js --from 2020 --to 2021 /tmp/out -c nz -p -v -r nz                                                                  
2020-01-01 New Year's Day
2020-01-02 Day after New Year's Day
2020-02-06 Waitangi Day
2020-04-10 Good Friday
2020-04-13 Easter Monday
2020-04-25 Anzac Day
2020-06-01 Queen's Birthday
2020-10-26 Labour Day
2020-12-25 Christmas Day
2020-12-26 Boxing Day
2021-01-01 New Year's Day
2021-01-02 Day after New Year's Day
2021-02-06 Waitangi Day
2021-04-02 Good Friday
2021-04-05 Easter Monday
2021-04-25 Anzac Day
2021-06-07 Queen's Birthday
2021-10-25 Labour Day
2021-12-25 Christmas Day
2021-12-26 Boxing Day
```

Should I merge this then? You are free to submit a solution for the special case when you have something robust. I will add a hint to the README that this special case exists (rather than tracking it as issue here).

**Comment by Mortein** [comment]
Yeah, please merge this. It's at least a step in the right direction and 10/11 ain't bad.

If I think of a nice way for the Provincial holidays, I'll make another PR.

**Comment by ypid** [comment]
All right. Merged and deployed.

**Pull request merged**
