### PR TITLE
Added holiday data for Vietnam

### PR DESCRIPTION
**Pull request by goodudetheboy**

### CODE REVIEW

**Comment by goodudetheboy** [comment]
I can't anyhow remove that `[new-lines] wrong new line character: expected \n` error. Also, when I run `yamllint --strict` on other XML file locally it all throws this error. Any ways to resolve this?

**Comment by ypid** [comment]
> I can't anyhow remove that [new-lines] wrong new line character: expected \n error. Also, when I run yamllint --strict on other YAML file locally it all throws this error. Any ways to resolve this?

You are using the wrong newline style in the files, probably because you are using a legacy operating system (Windows, see https://getgnulinux.org/). See https://en.wikipedia.org/wiki/Newline

I cannot push to your master branch. I thus created a new PR that fixes those issues and prepares it to be merged: #390

To support lunar year calendar, someone needs to implement it. I am hesitant to do it because of #300. I disabled the SH definitions.

I could merge #390 in this state. Does this look good to you?

```
./scripts/PH_SH_exporter.js --from 2021 --to 2022 /tmp/out -c vn -p -v
vn:
2021-01-01 Tết Dương Lịch
2021-03-08 Ngày Quốc tế Phụ nữ
2021-03-26 Ngày thành lập Đoàn Thanh niên Cộng sản Hồ Chí Minh
2021-04-30 Ngày Giải phóng miền Nam, Thống nhất Đất nước
2021-05-01 Ngày Quốc tế lao động
2021-06-01 Ngày Quốc tế Thiếu nhi
2021-09-02 Quốc Khánh
2021-11-20 Ngày Nhà giáo Việt Nam
2021-12-25 Lễ Giáng Sinh
2022-01-01 Tết Dương Lịch
2022-03-08 Ngày Quốc tế Phụ nữ
2022-03-26 Ngày thành lập Đoàn Thanh niên Cộng sản Hồ Chí Minh
2022-04-30 Ngày Giải phóng miền Nam, Thống nhất Đất nước
2022-05-01 Ngày Quốc tế lao động
2022-06-01 Ngày Quốc tế Thiếu nhi
2022-09-02 Quốc Khánh
2022-11-20 Ngày Nhà giáo Việt Nam
2022-12-25 Lễ Giáng Sinh
```

**Comment by goodudetheboy** [comment]
Yes, that LGTM! Thanks!

(I really need to switch to linux)

**Comment by ypid** [comment]
Deployed to https://openingh.ypid.de/, feel free to test.

**Pull request merged**
