### PR TITLE
Replace moment.js with Date.toLocaleString

### PR DESCRIPTION
**Pull request by KristjanESPERANTO**
That already happened with #250, but it wasn't complet.

### CODE REVIEW

**Review by ypid — CHANGES_REQUESTED** [review]
Can you clean up your commits a bit? Ref: https://chris.beams.io/posts/git-commit/

Otherwise LGTM :)

**Comment by KristjanESPERANTO** [comment]
Can you please give me a hint to what exactly you mean? I've already read these instructions, but apparently I haven't taken enough from them. In this case, I am just realizing that I have not used the imperative consistently, but it is probably not that alone.

**Comment by ypid** [comment]
The other thing that caught my eye was those two commits with the same description:

Replaced moment with Date.toLocaleString
Replaced moment with Date.toLocaleString

Can you try `git rebase` and then `git push -f`?

**Comment by KristjanESPERANTO** [comment]
Thank you for the explanation. But after `git rebase` I get `Current branch patch-2 is up to date.` and after `git push -f` I get `Everything up-to-date` - and nothing changed. I could close this PR and build a new one. Is it worth the effort?

**Comment by ypid** [comment]
Those commands were not complete on purpose. You should know what you are doing. You can look for "squash git rebase" and should find some tutorial to do it. I would propose to squash all 3 commits into one and then edit the commit message in one go. You don’t need to close this PR.

**Comment by KristjanESPERANTO** [comment]
I haven't figured out how to get rebase work. When I reset my branch, the PR was closed, so I created a new one: # 366.

**Comment by ypid** [comment]
I guess it is true, git is difficult. This command should do the trick `git rebase -i HEAD~~~` if you happen to need it next time.

**Pull request closed without merging**
