### PR TITLE
Adding Public and School Holidays for Hungary

### PR DESCRIPTION
**Pull request by AndreasTUHU**

### CODE REVIEW

**Comment by ypid** [comment]
Thanks! The PH definition looks good.

SH is tricky. Ideally, there would be a script which can generate the list like it is done for Germany. Might that be possible here? Because otherwise, the list will get outdated sooner or later (which reminds me that I should update SH definitions for Germany).

**Comment by AndreasTUHU** [comment]
I'm afraid that's not possible. The hungarian Ministry of Education publish the dates in spring for the next school year.

**Comment by ypid** [comment]
Hm, I understand. Maybe there are ical files available somewhere then?

**Comment by AndreasTUHU** [comment]
I do not know a ical calendar like this. I see two solutions to it. 
1. Delete the SH definition. At the moment there is one POI on Hungary with SH definition.
2. I set a recurring reminder to myself to update the repository
What is your opinion?

**Comment by ypid** [comment]
"I set a recurring reminder to myself to update the repository" Sounds good :wink: But whatever you prefer. Both options are ok with me.

**Comment by AndreasTUHU** [comment]
Reminder added :)

**Comment by ypid** [comment]
You closed? Should I merge the PH def or do you want to redo including SH?

**Comment by AndreasTUHU** [comment]
Sorry if I made a mistake. I assumed that I have to close the branch before you can merge it. The SH block in my patch is not enough? Should I do something else?

**Comment by ypid** [comment]
No problem. Closing a pull request normally means that you don’t want to add the patch to the project anymore. I will merge this later. Looks good, I just checked the SH definition:

```
$ ./PH_SH_exporter.js --verbose --from=2016 --to=2020 -s --country hu --region _hu /tmp/test
2016-11-01-2016-11-03 őszi szünet
2016-12-21-2016-12-30 téli szünet
$ ./PH_SH_exporter.js --verbose --from=2016 --to=2017 -s --country hu --region _hu /tmp/test
An error occurred during evaluation of the value "SH". Please submit a pull request: https://github.com/ypid/opening_hours.js. no SH definition

/home/user/p-y-dev/src/osm/oh-wc/opening_hours.js:6268
                        throw formatLibraryBugMessage(t('no SH definition', {
                                                      ^
                                                      An error occurred during evaluation of the value "SH". Please submit a pull request: https://github.com/ypid/opening_hours.js. no SH definition
                        }))
```

The thing which I noticed about the SH definition is that there are no common SH names for 2016 and 2017. Is that expected. I think the library expects that SH names are defined for each year.

Hear are the PHs for the next couple of years as calculated the lib:

```
./PH_SH_exporter.js --verbose --from=2016 --to=2023 -p --country hu --region _hu /tmp/test
2015-12-31 újév
2016-03-14 az 1848-as forradalom ünnepe
2016-03-26 húsvétvasárnap
2016-03-27 húsvéthétfő
2016-04-30 a munka ünnepe
2016-05-14 pünkösdvasárnap
2016-05-15 pünkösdhétfő
2016-08-19 az államalapítás ünnepe
2016-10-22 az 1956-os forradalom ünnepe
2016-10-31 mindenszentek
2016-12-24 karácsony
2016-12-25 karácsony másnap
2016-12-31 újév
2017-03-14 az 1848-as forradalom ünnepe
2017-04-15 húsvétvasárnap
2017-04-16 húsvéthétfő
2017-04-30 a munka ünnepe
2017-06-03 pünkösdvasárnap
2017-06-04 pünkösdhétfő
2017-08-19 az államalapítás ünnepe
2017-10-22 az 1956-os forradalom ünnepe
2017-10-31 mindenszentek
2017-12-24 karácsony
2017-12-25 karácsony másnap
2017-12-31 újév
2018-03-14 az 1848-as forradalom ünnepe
2018-03-31 húsvétvasárnap
2018-04-01 húsvéthétfő
2018-04-30 a munka ünnepe
2018-05-19 pünkösdvasárnap
2018-05-20 pünkösdhétfő
2018-08-19 az államalapítás ünnepe
2018-10-22 az 1956-os forradalom ünnepe
2018-10-31 mindenszentek
2018-12-24 karácsony
2018-12-25 karácsony másnap
2018-12-31 újév
2019-03-14 az 1848-as forradalom ünnepe
2019-04-20 húsvétvasárnap
2019-04-21 húsvéthétfő
2019-04-30 a munka ünnepe
2019-06-08 pünkösdvasárnap
2019-06-09 pünkösdhétfő
2019-08-19 az államalapítás ünnepe
2019-10-22 az 1956-os forradalom ünnepe
2019-10-31 mindenszentek
2019-12-24 karácsony
2019-12-25 karácsony másnap
2019-12-31 újév
2020-03-14 az 1848-as forradalom ünnepe
2020-04-11 húsvétvasárnap
2020-04-12 húsvéthétfő
2020-04-30 a munka ünnepe
2020-05-30 pünkösdvasárnap
2020-05-31 pünkösdhétfő
2020-08-19 az államalapítás ünnepe
2020-10-22 az 1956-os forradalom ünnepe
2020-10-31 mindenszentek
2020-12-24 karácsony
2020-12-25 karácsony másnap
2020-12-31 újév
2021-03-14 az 1848-as forradalom ünnepe
2021-04-03 húsvétvasárnap
2021-04-04 húsvéthétfő
2021-04-30 a munka ünnepe
2021-05-22 pünkösdvasárnap
2021-05-23 pünkösdhétfő
2021-08-19 az államalapítás ünnepe
2021-10-22 az 1956-os forradalom ünnepe
2021-10-31 mindenszentek
2021-12-24 karácsony
2021-12-25 karácsony másnap
2021-12-31 újév
2022-03-14 az 1848-as forradalom ünnepe
2022-04-16 húsvétvasárnap
2022-04-17 húsvéthétfő
2022-04-30 a munka ünnepe
2022-06-04 pünkösdvasárnap
2022-06-05 pünkösdhétfő
2022-08-19 az államalapítás ünnepe
2022-10-22 az 1956-os forradalom ünnepe
2022-10-31 mindenszentek
2022-12-24 karácsony
2022-12-25 karácsony másnap
2022-12-31 újév
2023-03-14 az 1848-as forradalom ünnepe
2023-04-08 húsvétvasárnap
2023-04-09 húsvéthétfő
2023-04-30 a munka ünnepe
2023-05-27 pünkösdvasárnap
2023-05-28 pünkösdhétfő
2023-08-19 az államalapítás ünnepe
2023-10-22 az 1956-os forradalom ünnepe
2023-10-31 mindenszentek
2023-12-24 karácsony
2023-12-25 karácsony másnap
```

**Comment by AndreasTUHU** [comment]
It looks like that the whole year slipped back with one day.
2015-12-31 újév should be 2016-01-01
2016-03-14 az 1848-as forradalom ünnepe should be 2016-03-15
and so on.
Is it a leap year problem?

What can I do with the SH block? Should I add the past 2015/16 school year or create fake 2017/18 date ranges?

**Comment by ypid** [comment]
> It looks like that the whole year slipped back with one day.

Thanks for noticing! Seems to be a problem with my local setup. Running it in a webbrowser still works with the latest version:
https://openingh.ypid.de/evaluation_tool/?EXP=PH&DATE=1451646120000&lat=48.7769&lon=9.1844&mode=0

I will need to investigate.

> What can I do with the SH block? Should I add the past 2015/16 school year or create fake 2017/18 date ranges?

Looks good for now. You can add older SH definitions if you have the time. This will allow people to go back in time. You do not need to create fake 2017/18 date ranges.

**Comment by AndreasTUHU** [comment]
Ok, I've added 2 more year.

**Comment by ypid** [comment]
[Fixed the Timezone problem in the script](https://github.com/opening-hours/opening_hours.js/commit/db8851128dc2e746d65199d58cb94f0e970c0c1d), updated my [post above](https://github.com/opening-hours/opening_hours.js/pull/182#issuecomment-247270698), merged and pushed changes into production (on both servers). Thanks. Looking forward to your yearly updates :wink:

**Comment by AndreasTUHU** [comment]
Thank you! See you in July 2017 :)

**Pull request merged**
