### PR TITLE
Added new holidays in Germany

### PR DESCRIPTION
**Pull request by StephanGeorg**

### CODE REVIEW

**Comment by ypid** [comment]
Thank you! Right in time ;-) Merged and deployed.

**Comment by StephanGeorg** [comment]
Is there a reason why you do not publish it to npm?

**Comment by TribeWeb** [comment]
It is published on npm - https://www.npmjs.com/package/opening_hours
BUT - none of the wonderful commits made in the last 2 years seem to be available until ver 3.6.0 is related. It would be very useful to have version 3.5.1, 3.5.2 etc released so we can benefit from the great work that is being contributed.

**Comment by ypid** [comment]
I wanted to have some time to do a proper release, but you are right. A release is long overdue. You can help with testing current master and tell me if it would work if I just released it to npm. I am not doing much/anything except this library with npm at the moment, sorry. Could you guys test it and confirm that it would work? That is the major reason I did not just release it.

**Comment by TribeWeb** [comment]
Hi @ypid. I am using the latest master branch as a repo/dependency in a project and it is working fine. I'm afraid I'm not able to feed back anything more specific than that.

**Pull request merged**
