### PR TITLE
Ph sh france

### PR DESCRIPTION
**Pull request by blef00fr**
Add SH definition  (and some PH) for France.
I'm not familiar with the yaml syntax, nor with Github.
I hope I don't make too many mistakes.

### CODE REVIEW

**Comment by ypid** [comment]
Thanks! The PR is tested so you can find hints about yaml here https://travis-ci.org/opening-hours/opening_hours.js/jobs/600377720.

So far, it looks good. I guess you generated the SH definitions? Can you include the script you used or point to it so that we can maintain the definitions long-term?

**Comment by blef00fr** [comment]
Hi,
I didn't use a script. I just collected the holidays dates from the Ministry of Education website and manually edited and filled out fr.yaml with Atom.
I quoted this source in the header commentary of the "school holidays" section.

**Comment by ypid** [comment]
Thanks @blef00fr for fixing the style issues. The other build failure would have required actually running the code using NodeJS and getting down to the command line so I jumped in there and fixed the remaining issues. Thanks for you work! Note one detail that is also mentioned in the holiday docs: The SH definitions need to be in order to work. I fixed that also.

As you added this manually, why did you mind to add the past year 2018? Sounds like unnecessary work ;-) I don’t mind having it as this also allows to use this lib for historical analysis and past years could be removed in optimized builds when needed (not yet implemented). I am just wondering :)

Feel free to keep an eye on the FR definitions over the following years and feel free to open more PRs to add upcoming years. Until then, I merged and deployed your changes to https://openingh.openstreetmap.de/

**Comment by blef00fr** [comment]
Thanks for fixing all remaining issues and merging my PR.
I had read about definition ordering in the doc, but I misunderstood it: I thought it meant that years had to be ordered in each holiday section. Sorry.
Why did I add 2018? I simply imitated what I saw in de.yaml without asking myself too many questions :-)
I will try to maintain SH definition in fr.yaml in the future.

**Comment by blef00fr** [comment]
Sorry, I have another question.
It exists another repo:
https://github.com/ypid/opening_hours.js
JOSM validator seems to use this one so it is still returning an error saying "no SH definition".
Do you plan to uptate fr.yaml on this repo or do I need to make another pull request on it?
Thanks.

**Comment by ypid** [comment]
You are welcome.

> Why did I add 2018? I simply imitated what I saw in de.yaml without asking myself too many questions :-)

Interesting ;-)

> "no SH definition"

This should be covered in JOSM. Basically, the JOSM validation gives this library a fake location where SH is defined. But I guess we did not freeze the time for the library so whether the library brings "no SH definition" or not depends on the time the evaluation is run. @don-vip, has anybody had the idea to look the time in JOSM like we do it for testing this library already?

Feel free to report this against JOSM when you are already using an up-to-date version of JOSM. I was not able to reproduce this right now though.

**Comment by don-vip** [comment]
I was not aware about the temporal definition of SH. AFAIK nobody had the idea of setting the time when calling the library. We can probably do it, but I'm not sure for how long we will still use opening_hours.js. I am really grateful about all the hard work you put in this nice library, but we're heavily dependent on the Oracle governance decisions about OpenJDK. They will remove JavaScript support from OpenJDK very soon (officially to ease maintenance, but probably to make their commercial GraalVM product more interesting), so we are currently investigating how to replace our JavaScript libraries by Java libraries (we can't afford to ship a full JavaScript engine only for a few nice libraries). See https://josm.openstreetmap.de/query?status=assigned&status=needinfo&status=new&status=reopened&keywords=~nashorn for details.

**Comment by ypid** [comment]
@don-vip Thanks for the update. I gave my input in [the ticket](https://josm.openstreetmap.de/ticket/18140) directly.

**Pull request merged**
