### PR TITLE
Added Croatian public holidays and school holidays

### PR DESCRIPTION
**Pull request by Janjko**

### CODE REVIEW

**Comment by ypid** [comment]
I had a look and saw that this work is incomplete. Can you set this PR? Can you check [the docs](https://github.com/opening-hours/opening_hours.js/blob/master/src/holidays/README.md) to see how to get this work ready and then change the pull request status from draft to ready again? I should get notified of this change to "ready". If not, feel free to ping me using `@ypid` in the comment.

**Comment by Janjko** [comment]
I added a `\src\holidays\nominatim_cache\hr.yml` file, i guess that is what was missing?

Now I get this output when I run the PH_SH_exporter.js:

 `sudo node ./scripts/PH_SH_exporter.js --verbose --from=2022 --to=2022 --school-holidays --country hr export_list.conf`

`An error occurred during evaluation of the value "SH". Please submit a pull request: https://github.com/opening-hours/opening_hours.js. There are no holidays (SH) defined for country hr.
Error creating new opening_hours('SH', {"place_id":"227339485","licence":"Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright","osm_type":"way","osm_id":"587745585","lat":"45.812984650000004","lon":"15.977982624964788","display_name":"Manduševac, Trg bana Josipa Jelačića, Mjesni odbor \"August Cesarec\", Gradska četvrt Gornji grad - Medveščak, Zagreb, Grad Zagreb, 10106, Hrvatska","address":{"country":"Hrvatska","country_code":"hr"},"boundingbox":["45.8129649","45.8130084","15.9779515","15.9780137"]}): Error: An error occurred during evaluation of the value "SH". Please submit a pull request: https://github.com/opening-hours/opening_hours.js. There are no holidays (SH) defined for country hr.. Please file a issue at https://github.com/opening-hours/opening_hours.js/issues`

Does this mean I formatted my yml wrong, or does this only work with data published on Github?

**Comment by ypid** [comment]
The docs says something about `index.js` ;-)

**Comment by ypid** [comment]
Merged and deployed to https://openingh.openstreetmap.de, thanks!

```
./scripts/PH_SH_exporter.js --verbose --from=2022 --to=2022 --school-holidays --country hr export_list.conf
hr:
2022-01-01--2022-01-09 Prvi dio zimskog odmora
2022-02-21--2022-02-27 Drugi dio zimskog odmora
2022-04-14--2022-04-24 Proljetni odmor
2022-06-23--2022-09-03 Ljetni praznici
2022-10-31--2022-11-01 Jesenski odmor
2022-12-27--2022-12-31 Prvi dio zimskog odmora
```

**Pull request merged**
