### PR TITLE
trying to add IE holidays

### PR DESCRIPTION
**Pull request by Gerw88**

### CODE REVIEW

**Comment by Gerw88** [comment]
@ypid YAML verified on yamllint.com, and it looks ok to me. Unfortunately, can't figure out what would be keeping it from building?

**Comment by ypid** [comment]
@Gerw88 Thanks for your work. I already fixed the format locally, don’t worry ;-) Just give me a minute to see the finished work.

**Comment by Gerw88** [comment]
Thanks for your help!

**Comment by ypid** [comment]
You are welcome. The holidays generated look like this:

```
$ ./PH_SH_exporter.js --from 2016 --to 2019 /tmp/out -c ie -p -v
2016-01-01 New Year’s Day
2016-03-21 St Patrick’s Day
2016-03-25 Good Friday
2016-03-28 Easter Monday
2016-05-02 May Bank Holiday
2016-06-06 June Bank Holiday
2016-08-01 August Bank Holiday
2016-10-31 October Bank Holiday (Halloween)
2016-12-25 Christmas
2016-12-26 St Stephen’s Day
2016-12-27 Bank Holiday
2017-01-01 New Year’s Day
2017-03-20 St Patrick’s Day
2017-04-14 Good Friday
2017-04-17 Easter Monday
2017-05-01 May Bank Holiday
2017-06-05 June Bank Holiday
2017-08-07 August Bank Holiday
2017-10-30 October Bank Holiday (Halloween)
2017-12-25 Christmas
2017-12-26 St Stephen’s Day
2017-12-27 Bank Holiday
2018-01-01 New Year’s Day
2018-03-19 St Patrick’s Day
2018-03-30 Good Friday
2018-04-02 Easter Monday
2018-05-07 May Bank Holiday
2018-06-04 June Bank Holiday
2018-08-06 August Bank Holiday
2018-10-29 October Bank Holiday (Halloween)
2018-12-25 Christmas
2018-12-26 St Stephen’s Day
2018-12-27 Bank Holiday
2019-01-01 New Year’s Day
2019-03-18 St Patrick’s Day
2019-04-19 Good Friday
2019-04-22 Easter Monday
2019-05-06 May Bank Holiday
2019-06-03 June Bank Holiday
2019-08-05 August Bank Holiday
2019-10-28 October Bank Holiday (Halloween)
2019-12-25 Christmas
2019-12-26 St Stephen’s Day
2019-12-27 Bank Holiday
```

Which matches https://www.officeholidays.com/countries/ireland/index.php

I had to fix a few calculations. St Patrick’s Day is not always on the 17 but on the 17 if it is a Monday and if not the following Monday which is how I implemented it now. Can you compare the generated holidays above with an official source to cross check?

**Comment by Gerw88** [comment]
Not exactly - "St Patrick's Day" is always March 17th, regardless how the day falls within the week.

Seems if March 17th is between Tuesday and Friday, then that day is St Patrick's day (and celebrated as a national holiday). In 2020, for instance, both fall on a Tuesday.
If it's Saturday, Sunday, Monday, then the next Monday is observed as a national holiday, as per the definition _'nextMonday17March'_ you wrote.

Incidentally, happy St Patrick's Day!

**Comment by ypid** [comment]
According to https://www.officeholidays.com/countries/ireland/st_patricks_day.php:

> St. Patrick's Day is celebrated on 17 March as a holiday in the Republic of Ireland and a bank holiday in Northern Ireland. If 17 March falls on a weekend, the following Monday will be a holiday in both countries.

```
./PH_SH_exporter.js --from 2016 --to 2020 /tmp/out -c ie -p -v  | grep 'Patrick' | tac 
2020-03-17 St Patrick’s Day
2019-03-18 St Patrick’s Holiday (Monday)
2019-03-17 St Patrick’s Day
2018-03-19 St Patrick’s Holiday (Monday)
2018-03-17 St Patrick’s Day
2017-03-17 St Patrick’s Day
2016-03-17 St Patrick’s Day
```

I hope this is correct now? It required a change of the definition format.

**Comment by Gerw88** [comment]
Fantastic, these dates are correct.

**Comment by ypid** [comment]
Merged, added a test and deployed.

**Pull request closed without merging**
